var juegos = [
  {
    "nombre": "Pac-Man",
    "precio": 4.75,
    "fecha": 2016,
    "desarrollador": "Bandai Namco Entertainment Inc.",
    "valoracion": 7.6,
    "categorias": ["Arcade", "Retro"],
  },
  {
    "nombre": "Assassin's Creed Odyssey",
    "precio": 42,
    "fecha": 2018,
    "desarrollador": "ubisoft",
    "valoracion": 8.2,
    "categorias": ["Acción", "Aventuras", "Histórico"],
  },
  {
    "nombre": "Pro Evolution Soccer 2019",
    "fecha": 2018,
    "precio": 39,
    "desarrollador": "Konami",
    "valoracion": 7.9,
    "categorias": ["Deportes", "Fútbol"],
  },
  {
    "nombre": "Fallout 76",
    "precio": 40,
    "fecha": 2018,
    "desarrollador": "Bethesda Game Studios",
    "valoracion": 8.0,
    "categorias": ["Acción", "Aventuras", "Rol"],
  },
  {
    "nombre": "Red Dead Redemption II",
    "precio": 47,
    "fecha": 2018,
    "desarrollador": "Rockstar Studios",
    "valoracion": 8.6,
    "categorias": ["Acción", "Aventuras"],
  },
  {
    "nombre": "Spider-Man",
    "precio": 39,
    "fecha": 2018,
    "desarrollador": "Insomniac Games",
    "valoracion": 7.9,
    "categorias": ["Acción", "Superhéores"],
  },
  {
    "nombre": "Far Cry 5",
    "precio": 35,
    "fecha": 2018,
    "desarrollador": "Ubisoft",
    "valoracion": 7.7,
    "categorias": ["Acción", "Shooter"],
  },
  {
    "nombre": "God of War",
    "precio": 40,
    "fecha": 2018,
    "desarrollador": "SCE Santa Monica Studio",
    "valoracion": 8.0,
    "categorias": ["Acción", "Aventuras"],
  },
  {
    "nombre": "Shadow of the Tomb Raider",
    "precio": 40,
    "fecha": 2018,
    "desarrollador": "Eidos Montréal",
    "valoracion": 8.1,
    "categorias": ["Acción", "Aventuras"],
  }
]
